//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllFile
    {
        public AllFile()
        {
            this.Findings = new HashSet<Finding>();
            this.Images = new HashSet<Image>();
            this.Sounds = new HashSet<Sound>();
            this.Videos = new HashSet<Video>();
        }
    
        public int FileID { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public int FileSize { get; set; }
        public int FileExtensionID { get; set; }
        public System.DateTime FileCreated { get; set; }
        public System.DateTime FileAdded { get; set; }
        public System.DateTime FileChanged { get; set; }
        public bool FileIsOnDrive { get; set; }
    
        public virtual FileExtension FileExtension { get; set; }
        public virtual ICollection<Finding> Findings { get; set; }
        public virtual ICollection<Image> Images { get; set; }
        public virtual ICollection<Sound> Sounds { get; set; }
        public virtual ICollection<Video> Videos { get; set; }
    }
}
