//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Finding
    {
        public int FindingID { get; set; }
        public int FileID { get; set; }
        public int FindingTypeID { get; set; }
    
        public virtual AllFile AllFile { get; set; }
        public virtual FindingType FindingType { get; set; }
    }
}
