//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sound
    {
        public int SoundID { get; set; }
        public int FileID { get; set; }
        public string SoundArtist { get; set; }
        public string SoundName { get; set; }
        public string SoundAlbum { get; set; }
        public System.TimeSpan SoundDuration { get; set; }
        public int SoundViews { get; set; }
        public System.TimeSpan SoundCurrentPosition { get; set; }
    
        public virtual AllFile AllFile { get; set; }
    }
}
