//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Video
    {
        public int VideoID { get; set; }
        public int FileID { get; set; }
        public System.TimeSpan VideoDuration { get; set; }
        public int VideoViews { get; set; }
        public System.TimeSpan VideoCurrentPosition { get; set; }
    
        public virtual AllFile AllFile { get; set; }
    }
}
